# Generated by Django 3.2.8 on 2021-10-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211010_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
