# Generated by Django 3.2.8 on 2021-10-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoice_items', to='myapp.Item'),
        ),
    ]
